services:
  - type: web
    name: line-bot-hermes
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 line_webhook_render_bot.py"
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: LINE_WEBHOOK_PATH
        value: /line/webhook
      - key: CHANNEL_ACCESS_TOKEN
        sync: false
